
using System;

namespace Resources.App_LocalResources
{
    partial class Resource {
        /// <summary>
        /// Autogenerated constants for Resource resources
        /// </summary>
        public static class Keys
        {
            /// <summary>
           /// ActionName
            /// </summary>           
            public const string Action="Action";

            /// <summary>
           /// ActionRequire
            /// </summary>           
            public const string ActionRequire="ActionRequire";

            /// <summary>
           /// AdminLayout_View_AdminText
            /// </summary>           
            public const string AdminLayout_View_AdminText="AdminLayout_View_AdminText";

            /// <summary>
           /// ApplicationRole.Description
            /// </summary>           
            public const string ApplicationRole_Description="ApplicationRole_Description";

            /// <summary>
           /// ControllerName
            /// </summary>           
            public const string Controller="Controller";

            /// <summary>
           /// PermissionViewModel_Description
            /// </summary>           
            public const string PermissionViewModel_Description="PermissionViewModel_Description";

            }
    }


}
