var $.AdminResources = {
    'DepartmentViewModelName' : 'DepartmentViewModelName',
    'AdminLayout_View_AdminText' : 'AdminLayout_View_AdminText',
    'PermissionViewModel_RoleName' : 'PermissionViewModel_RoleName',
    'ActionRequire' : 'ActionRequire',
    'Controller' : 'ControllerName',
    'ApplicationRole_Description' : 'ApplicationRole.Description',
    'DepartmentViewModelId' : 'DepartmentViewModelId',
    'AdminLayout_ActionLink_UserAdmin' : 'AdminLayout_ActionLink_UserAdmin',
    'Action' : 'ActionName',
    'AdminLayout_ActionLink_DeptAdmin' : 'AdminLayout_ActionLink_DeptAdmin',
    'PermissionViewModel_Description' : 'PermissionViewModel_Description',
    'RoleViewModel_Name' : 'RoleViewModel_Name',
    'AdminLayout_View_FrontEndText' : 'AdminLayout_View_FrontEndText',
};