using Xunit;
using WebAuth.Areas.Admin.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WebAuth.Areas.Admin.Controllers.Tests
{
    /// <summary>
    /// DepartmentControllerTests 
    /// </summary>
    /// <remarks>It was generated by VS2015 </remarks>
    public class DepartmentControllerTests
    {
        /// <summary>
        /// Detailses the test.
        /// </summary>
        /// <returns></returns>
        [Fact()]
        public async Task DetailsTest()
        {
            var departmentController = new DepartmentController();
            var results=await departmentController.Details(0);
            Assert.NotNull(results);
        }

        /// <summary>
        /// Edits the test.
        /// </summary>
        [Fact()]
        public async void EditTest()
        {
            var departmentController = new DepartmentController();
            var results = await departmentController.Edit(0);
            Assert.NotNull(results);
        }
    }
}