//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// T_BD_PushMessage
    /// </summary>
    public partial class T_BD_PushMessage
    {
        public int Id { get; set; }
        /// <summary>
        /// Gets or sets the content of the MSG.
        /// </summary>
        /// <value>
        /// The content of the MSG.
        /// </value>
        public string MsgContent { get; set; }
        /// <summary>
        /// Gets or sets the MSG title.
        /// </summary>
        /// <value>
        /// The MSG title.
        /// </value>
        public string MsgTitle { get; set; }
        /// <summary>
        /// Gets or sets the type of the MSG.
        /// </summary>
        /// <value>
        /// The type of the MSG.
        /// </value>
        public int MsgType { get; set; }
        /// <summary>
        /// Gets or sets the type of the MSG send.
        /// </summary>
        /// <value>
        /// The type of the MSG send.
        /// </value>
        public string MsgSendType { get; set; }
        /// <summary>
        /// Gets or sets the remark.
        /// </summary>
        /// <value>
        /// The remark.
        /// </value>
        public string Remark { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public Nullable<int> Userid { get; set; }
        public bool IsRead { get; set; }

    }



}
