//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BD_PushMessageConfig
    {
        public int Id { get; set; }
        public Nullable<int> Userid { get; set; }
        public int MsgType { get; set; }
        public System.DateTime UpdateTime { get; set; }
        /// <summary>
        /// Updator
        /// </summary>
        public Nullable<int> Updator { get; set; }
    

    }
}
